### ISSUE TITLE
Error while trying to run the app

### ISSUE THREAD

**Issue by chen-ni** [linzebing/MiniSpark#14]
Got this error while trying to run the app in IntelliJ on MacOS:

```
org.apache.thrift.transport.TTransportException: java.net.UnknownHostException: ip-172-31-75-241.ec2.internal
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226)
	at minispark.Master.<init>(Master.java:46)
	at minispark.Scheduler.<init>(Scheduler.java:26)
	at minispark.SparkContext.<init>(SparkContext.java:22)
	at minispark.App.SparkPi(App.java:74)
	at minispark.App.main(App.java:91)
Caused by: java.net.UnknownHostException: ip-172-31-75-241.ec2.internal
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	... 5 more
```

**Comment by zhiyangdata** [comment]
Change ip-172-31-75-241.ec2.internal to your own cluster.
